/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrafficRouteImport } from './routes/api/traffic'
import { Route as ApiFindRouteRouteImport } from './routes/api/find-route'
import { Route as ApiAlternateRoutesRouteImport } from './routes/api/alternate-routes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrafficRoute = ApiTrafficRouteImport.update({
  id: '/api/traffic',
  path: '/api/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFindRouteRoute = ApiFindRouteRouteImport.update({
  id: '/api/find-route',
  path: '/api/find-route',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlternateRoutesRoute = ApiAlternateRoutesRouteImport.update({
  id: '/api/alternate-routes',
  path: '/api/alternate-routes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/alternate-routes': typeof ApiAlternateRoutesRoute
  '/api/find-route': typeof ApiFindRouteRoute
  '/api/traffic': typeof ApiTrafficRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/alternate-routes': typeof ApiAlternateRoutesRoute
  '/api/find-route': typeof ApiFindRouteRoute
  '/api/traffic': typeof ApiTrafficRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/alternate-routes': typeof ApiAlternateRoutesRoute
  '/api/find-route': typeof ApiFindRouteRoute
  '/api/traffic': typeof ApiTrafficRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/alternate-routes' | '/api/find-route' | '/api/traffic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/alternate-routes' | '/api/find-route' | '/api/traffic'
  id:
    | '__root__'
    | '/'
    | '/api/alternate-routes'
    | '/api/find-route'
    | '/api/traffic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAlternateRoutesRoute: typeof ApiAlternateRoutesRoute
  ApiFindRouteRoute: typeof ApiFindRouteRoute
  ApiTrafficRoute: typeof ApiTrafficRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/traffic': {
      id: '/api/traffic'
      path: '/api/traffic'
      fullPath: '/api/traffic'
      preLoaderRoute: typeof ApiTrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/find-route': {
      id: '/api/find-route'
      path: '/api/find-route'
      fullPath: '/api/find-route'
      preLoaderRoute: typeof ApiFindRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alternate-routes': {
      id: '/api/alternate-routes'
      path: '/api/alternate-routes'
      fullPath: '/api/alternate-routes'
      preLoaderRoute: typeof ApiAlternateRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAlternateRoutesRoute: ApiAlternateRoutesRoute,
  ApiFindRouteRoute: ApiFindRouteRoute,
  ApiTrafficRoute: ApiTrafficRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
